apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: chitsaz/simple-api:f952f9e832793935c7f5979122783d5876603e15
          ports:
            - containerPort: 8080