apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: chitsaz/simple-api:e5f196dd9ac18cf42a9ffd8764313d659103d97c
          ports:
            - containerPort: 8080