apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: chitsaz/simple-api:16b975303d0851725f9ff18dfd31facb7ccc61f9
          ports:
            - containerPort: 8080