name: CI Build and Update GitOps

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-api:${{ github.sha }} ./app-repo

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-api:${{ github.sha }}
      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Contents:"
          ls -la
          echo "Looking for deployment.yaml everywhere:"
          find . -name "*.yaml" -o -name "*.yml" | grep -i deployment
          echo "Looking for gitops-repo directories:"
          find . -type d -name "*gitops*"
      - name: Update deployment file
        run: |
          #sed -i "s/REPLACE_TAG/${{ github.sha }}/" gitops-repo/deployment.yaml
          sed -i "s|simple-api:.*|simple-api:${{ github.sha }}|" gitops-repo/deployment.yaml
          cat gitops-repo/deployment.yaml
          git diff
          
      - name: Commit and push GitOps change
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git pull origin main --rebase

          git add gitops-repo/deployment.yaml
          git commit -m "update image tag ${{ github.sha }}" || echo "no changes"
          git push